### ISSUE TITLE
Runtime changed Date

### ISSUE THREAD

**Issue by timber-they** [sevenmaster/register#1]
When the Year-Cycle-Date is changed, the entries get in a wrong order (the first entry still is the first one - even though it'd may have to be the second one then)

**Comment by timber-they** [comment]
This is kind of fixed now - we just have to generate empty entries for the new dates we get by changing the cycle

**Comment by TeEmZe** [comment]
This is kind of fixed now - we just have to generate empty entries for the new dates we get by changing the cycle

**Comment by timber-they** [comment]
FIXED :) I simply wrote a wonderful method that creates the missing week-data-objects.
